version: 2

# Note: the module version here is just used to run tests via the Spacelift private module registry.
# The value can be changed as needed and doesn't need to match the tagged module version.
module_version: "1.10.0"

tests:
  - name: Custom VPC
    project_root: examples/custom-vpc
    environment:
      TF_VAR_aws_region: eu-north-1

  - name: Custom S3 retention
    project_root: examples/custom-s3-retention
    environment:
      TF_VAR_aws_region: eu-north-1

  - name: SQS Enabled
    project_root: examples/sqs-enabled
    environment:
      TF_VAR_aws_region: eu-north-1
